In [6]:
#IMPORTS

import pandas as pd

In [7]:
clean_analysis_df = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_with_descriptions.xlsx')

In [8]:
display(clean_analysis_df)

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_48,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Going through the sections of the Climate of H...,Going through the sections of the Climate of H...,Going through the sections of the Climate of H...,Please answer the following questions about cl...,Please answer the following questions about cl...,Please answer the following questions about cl...,Please answer the following questions about cl...,Please answer the following questions about cl...,Please answer the following questions about cl...,Please answer the following questions about cl...
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID47_80""}","{""ImportId"":""QID47_81""}","{""ImportId"":""QID47_82""}","{""ImportId"":""QID49_1""}","{""ImportId"":""QID49_2""}","{""ImportId"":""QID49_3""}","{""ImportId"":""QID49_4""}","{""ImportId"":""QID49_5""}","{""ImportId"":""QID49_6""}","{""ImportId"":""QID49_7""}"
2,2024-01-24 16:52:41,2024-01-24 19:29:43,IP Address,155.98.131.0,100,9422,True,2024-01-24 19:29:44,R_7JjAHZBazmS3x73,NaN,...,A little bit,A little bit,Not at all,Moderately,Moderately,A little bit,A little bit,A little bit,A little bit,Not at all
3,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100,10464,True,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,A lot,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all
4,2024-01-24 16:36:52,2024-01-24 19:30:16,IP Address,155.98.131.4,100,10404,True,2024-01-24 19:30:17,R_6wQQHroz2FD6m6G,NaN,...,Moderately,A lot,Not at all,A little bit,Not at all,A little bit,Not at all,Moderately,A little bit,A lot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2024-04-06 14:36:07,2024-04-06 15:32:22,IP Address,155.98.131.0,100,3375,True,2024-04-06 15:32:23,R_62alnCFIpW4CjnZ,NaN,...,A little bit,A little bit,Not at all,A great deal,Moderately,A little bit,Not at all,Not at all,A little bit,Moderately
185,2024-04-06 14:35:16,2024-04-06 15:30:12,IP Address,155.98.131.7,100,3296,True,2024-04-06 15:30:13,R_3lv4Z5yPo0XEf9D,NaN,...,A little bit,Moderately,Not at all,A lot,A lot,A lot,A lot,Not at all,A lot,A great deal
186,2024-04-06 14:34:46,2024-04-06 15:31:05,IP Address,155.98.131.5,100,3378,True,2024-04-06 15:31:05,R_3fNzlkOukIhRV9V,NaN,...,Not at all,Moderately,Not at all,A great deal,A great deal,A great deal,A great deal,A little bit,A great deal,A great deal
187,2024-04-06 13:48:14,2024-04-06 16:11:15,IP Address,155.98.131.3,100,8581,True,2024-04-06 16:11:16,R_60pdvn9w8Nkf2se,NaN,...,A lot,Not at all,Not at all,A little bit,A little bit,Not at all,A little bit,A little bit,A little bit,Moderately
188,2024-04-06 15:11:50,2024-04-06 16:08:12,IP Address,155.98.131.1,100,3382,True,2024-04-06 16:08:13,R_5zHgVIAkjwVgZIh,NaN,...,Moderately,Not at all,Not at all,A little bit,A little bit,Not at all,Not at all,Not at all,Not at all,Not at all

In [26]:
#Rename all emotion columns to be more descriptive
def clean_data(df):
    sections = {
        'emotion_aspen': 'aspen',
        'emotion_health_impacts': 'here_now_impacts',
        'emotions_climate_sol': 'build_momentum',
        'emotions_connecting': 'connecting'
    }
    emotions = ['indifferent', 'sad', 'hopeless', 'interested', 'afraid_scared',
                'optimistic_hopeful', 'anxious', 'inspired', 'angry_frustrated',
                'happy', 'guilty', 'numb', 'stressed']
    
    rename_mapping = {
        **{f'{old}_{i}': f'{new}_{emotion}' 
           for old, new in sections.items()
           for i, emotion in enumerate(emotions, 1)},
        'relatable_health': 'relatable_here_now'
    }
    #drop the first two rows of the dataframe because they are not needed
    return df[(df.index != 0) & (df.index != 1)].rename(columns=rename_mapping)

clean_analysis_df = clean_data(clean_analysis_df.copy())
clean_analysis_df.head()

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_48,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7
2,2024-01-24 16:52:41,2024-01-24 19:29:43,IP Address,155.98.131.0,100,9422,True,2024-01-24 19:29:44,R_7JjAHZBazmS3x73,NaN,...,A little bit,A little bit,Not at all,Moderately,Moderately,A little bit,A little bit,A little bit,A little bit,Not at all
3,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100,10464,True,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,A lot,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all
4,2024-01-24 16:36:52,2024-01-24 19:30:16,IP Address,155.98.131.4,100,10404,True,2024-01-24 19:30:17,R_6wQQHroz2FD6m6G,NaN,...,Moderately,A lot,Not at all,A little bit,Not at all,A little bit,Not at all,Moderately,A little bit,A lot
5,2024-01-24 19:30:11,2024-01-26 15:17:30,IP Address,155.98.131.2,100,157638,True,2024-01-26 15:17:31,R_6PO33vlaXgyLTdn,NaN,...,Extremely,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,A little bit,A great deal
6,2024-01-24 19:30:17,2024-01-26 15:20:15,IP Address,155.98.131.4,100,157797,True,2024-01-26 15:20:16,R_6rvUHTQiMej0h1A,NaN,...,Not at all,Not at all,Not at all,A lot,Moderately,Moderately,A little bit,Not at all,Not at all,Not at all

In [23]:
# Create dataframes with simplified column names, including ida
aspen_emotion_df = clean_analysis_df[['ida', 'aspen_indifferent', 'aspen_sad', 'aspen_hopeless', 'aspen_interested', 
    'aspen_afraid_scared', 'aspen_optimistic_hopeful', 'aspen_anxious', 'aspen_inspired', 
    'aspen_angry_frustrated', 'aspen_happy', 'aspen_guilty', 'aspen_numb', 'aspen_stressed']]
aspen_emotion_df.columns = ['ida'] + [col.replace('aspen_', '') for col in aspen_emotion_df.columns if col != 'ida']

here_now_impacts_emotion_df = clean_analysis_df[['ida', 'here_now_impacts_indifferent', 'here_now_impacts_sad', 
    'here_now_impacts_hopeless', 'here_now_impacts_interested', 'here_now_impacts_afraid_scared', 
    'here_now_impacts_optimistic_hopeful', 'here_now_impacts_anxious', 'here_now_impacts_inspired', 
    'here_now_impacts_angry_frustrated', 'here_now_impacts_happy', 'here_now_impacts_guilty', 
    'here_now_impacts_numb', 'here_now_impacts_stressed']]
here_now_impacts_emotion_df.columns = ['ida'] + [col.replace('here_now_impacts_', '') for col in here_now_impacts_emotion_df.columns if col != 'ida']

build_momentum_emotion_df = clean_analysis_df[['ida', 'build_momentum_indifferent', 'build_momentum_sad', 
    'build_momentum_hopeless', 'build_momentum_interested', 'build_momentum_afraid_scared', 
    'build_momentum_optimistic_hopeful', 'build_momentum_anxious', 'build_momentum_inspired', 
    'build_momentum_angry_frustrated', 'build_momentum_happy', 'build_momentum_guilty', 
    'build_momentum_numb', 'build_momentum_stressed']]
build_momentum_emotion_df.columns = ['ida'] + [col.replace('build_momentum_', '') for col in build_momentum_emotion_df.columns if col != 'ida']

connecting_emotion_df = clean_analysis_df[['ida', 'connecting_indifferent', 'connecting_sad', 'connecting_hopeless', 
    'connecting_interested', 'connecting_afraid_scared', 'connecting_optimistic_hopeful', 'connecting_anxious', 
    'connecting_inspired', 'connecting_angry_frustrated', 'connecting_happy', 'connecting_guilty', 
    'connecting_numb', 'connecting_stressed']]
connecting_emotion_df.columns = ['ida'] + [col.replace('connecting_', '') for col in connecting_emotion_df.columns if col != 'ida']

display(connecting_emotion_df)

,ida,indifferent,sad,hopeless,interested,afraid_scared,optimistic_hopeful,anxious,inspired,angry_frustrated,happy,guilty,numb,stressed
2,24012401BF,Not at all,Not at all,Not at all,Only a little,Not at all,Only a little,Not at all,Only a little,Not at all,Only a little,Not at all,Not at all,Not at all
3,24012401MG,Only a little,Not at all,Not at all,A moderate amount,Not at all,A great deal,Not at all,A moderate amount,Not at all,Only a little,Not at all,Not at all,Not at all
4,24012401PM,Not at all,Not at all,Not at all,A moderate amount,Not at all,A moderate amount,Only a little,Only a little,A moderate amount,Only a little,Only a little,Not at all,Only a little
5,24012601LS,Not at all,Only a little,Only a little,A moderate amount,Only a little,A great deal,Not at all,Only a little,Only a little,Only a little,Only a little,Not at all,Not at all
6,24012601RS,Only a little,Not at all,Not at all,A great deal,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,24040610EC,Not at all,Not at all,Not at all,A great deal,Not at all,A great deal,Not at all,Only a little,Not at all,A moderate amount,Not at all,Not at all,Not at all
185,24040610MC,Only a little,Not at all,Not at all,Only a little,Not at all,Not at all,Only a little,Not at all,A moderate amount,Not at all,Not at all,Not at all,Only a little
186,24040610OW,A moderate amount,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little
187,24040611KS,Not at all,Not at all,Only a little,A great deal,Only a little,A moderate amount,Not at all,A moderate amount,Not at all,A moderate amount,Not at all,Not at all,Not at all
188,24040611MM,Not at all,Only a little,Not at all,A great deal,Only a little,A moderate amount,Only a little,A great deal,Only a little,Only a little,Not at all,Only a little,Only a little

In [11]:
# Add identifier column to each section dataframe
aspen_emotion_df['section'] = 'aspen'
here_now_impacts_emotion_df['section'] = 'here_now_impacts'
build_momentum_emotion_df['section'] = 'build_momentum'
connecting_emotion_df['section'] = 'connecting'

C:\Users\Hailey Sherman\AppData\Local\Temp\ipykernel_20860\1890682314.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aspen_emotion_df['section'] = 'aspen'
C:\Users\Hailey Sherman\AppData\Local\Temp\ipykernel_20860\1890682314.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  here_now_impacts_emotion_df['section'] = 'here_now_impacts'
C:\Users\Hailey Sherman\AppData\Local\Temp\ipykernel_20860\1890682314.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  build_momentum_emotion_df['section'] = 'build_momentum'
C:\Users\Hailey Sherman\AppData\Local\Temp\ipykernel_20860\1890682314.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  connecting_emotion_df['section'] = 'connecting'

,indifferent,sad,hopeless,interested,afraid_scared,optimistic_hopeful,anxious,inspired,angry_frustrated,happy,guilty,numb,stressed,section
0,Only a little,Not at all,Not at all,Only a little,Only a little,A moderate amount,Only a little,Only a little,Not at all,Only a little,Not at all,Not at all,Only a little,aspen
1,Not at all,Not at all,Not at all,A moderate amount,Not at all,Only a little,Not at all,Only a little,Not at all,Only a little,Not at all,A moderate amount,Not at all,aspen
2,Only a little,Only a little,Not at all,A moderate amount,Only a little,A moderate amount,A moderate amount,A moderate amount,Not at all,A moderate amount,Not at all,Not at all,Only a little,aspen
3,Not at all,Only a little,Not at all,Only a little,Not at all,A great deal,Not at all,Only a little,Not at all,Only a little,Only a little,Only a little,Only a little,aspen
4,Only a little,Not at all,Not at all,Only a little,Not at all,Only a little,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,Not at all,aspen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,Not at all,Not at all,Not at all,A great deal,Not at all,A great deal,Not at all,Only a little,Not at all,A moderate amount,Not at all,Not at all,Not at all,connecting
744,Only a little,Not at all,Not at all,Only a little,Not at all,Not at all,Only a little,Not at all,A moderate amount,Not at all,Not at all,Not at all,Only a little,connecting
745,A moderate amount,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,Only a little,connecting
746,Not at all,Not at all,Only a little,A great deal,Only a little,A moderate amount,Not at all,A moderate amount,Not at all,A moderate amount,Not at all,Not at all,Not at all,connecting
747,Not at all,Only a little,Not at all,A great deal,Only a little,A moderate amount,Only a little,A great deal,Only a little,Only a little,Not at all,Only a little,Only a little,connecting

In [24]:
#combine all dataframes so there is a column for each exhibit section, and row for each emotion per participant

# Create a list of all emotions (taking from any of the dataframes since they're the same)
emotions = [col for col in aspen_emotion_df.columns if col not in ['ida', 'section']]

# Initialize empty lists to store data
all_data = []

# For each participant ID and emotion combination
for ida in aspen_emotion_df['ida'].unique():
    for emotion in emotions:
        row_data = {
            'ida': ida,
            'emotion': emotion,
            'aspen': aspen_emotion_df[aspen_emotion_df['ida'] == ida][emotion].iloc[0],
            'here_now_impacts': here_now_impacts_emotion_df[here_now_impacts_emotion_df['ida'] == ida][emotion].iloc[0],
            'build_momentum': build_momentum_emotion_df[build_momentum_emotion_df['ida'] == ida][emotion].iloc[0],
            'connecting': connecting_emotion_df[connecting_emotion_df['ida'] == ida][emotion].iloc[0]
        }
        all_data.append(row_data)

# Create the reshaped dataframe
emotions_by_section_df = pd.DataFrame(all_data)

# Display the reshaped dataframe
display(emotions_by_section_df)

,ida,emotion,aspen,here_now_impacts,build_momentum,connecting
0,24012401BF,indifferent,Only a little,Not at all,Not at all,Not at all
1,24012401BF,sad,Not at all,A moderate amount,Only a little,Not at all
2,24012401BF,hopeless,Not at all,Only a little,Not at all,Not at all
3,24012401BF,interested,Only a little,A moderate amount,A moderate amount,Only a little
4,24012401BF,afraid_scared,Only a little,A moderate amount,Only a little,Not at all
...,...,...,...,...,...,...
2426,24040611MM,angry_frustrated,A great deal,A great deal,A moderate amount,Only a little
2427,24040611MM,happy,Only a little,Not at all,Not at all,Only a little
2428,24040611MM,guilty,Not at all,Not at all,Not at all,Not at all
2429,24040611MM,numb,Not at all,Not at all,Not at all,Only a little
2430,24040611MM,stressed,Not at all,Not at all,Only a little,Only a little

In [25]:
emotions_by_section_df.to_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/emotions_by_section_df.xlsx', index=False)

In [ ]:
# Combine all dataframes vertically (with column for each emotion)
combined_emotions_df = pd.concat([
    aspen_emotion_df,
    here_now_impacts_emotion_df,
    build_momentum_emotion_df,
    connecting_emotion_df
], axis=0)

# Reset index to avoid duplicate indices
combined_emotions_df = combined_emotions_df.reset_index(drop=True)

# Display the combined dataframe
display(combined_emotions_df)

In [13]:
combined_emotions_df.to_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/combined_emotions_df_for_plots.xlsx', index=False)

In [14]:
# Convert to long format
long_emotions_df = combined_emotions_df.melt(
    id_vars=['section'],  # Keep the section column as an identifier
    var_name='emotion',   # Name for the column containing emotion types
    value_name='response' # Name for the column containing response values
)

# Reset index
long_emotions_df = long_emotions_df.reset_index(drop=True)

# Display first few rows to verify
display(long_emotions_df)

         section      emotion       response
0          aspen  indifferent  Only a little
1          aspen  indifferent     Not at all
2          aspen  indifferent  Only a little
3          aspen  indifferent     Not at all
4          aspen  indifferent  Only a little
...          ...          ...            ...
9719  connecting     stressed     Not at all
9720  connecting     stressed  Only a little
9721  connecting     stressed  Only a little
9722  connecting     stressed     Not at all
9723  connecting     stressed  Only a little

[9724 rows x 3 columns]

In [ ]:
#long format df tests

# Test 1: Check we have the expected number of rows
expected_rows = len(combined_emotions_df) * len(combined_emotions_df.columns.drop('section'))
print(f"Expected rows: {expected_rows}")
print(f"Actual rows: {len(long_emotions_df)}")
print(f"Match: {expected_rows == len(long_emotions_df)}\n")

# Test 2: Check we have all sections represented with equal counts
print("Sections and their counts:")
section_counts = long_emotions_df['section'].value_counts()
print(section_counts)
print(f"Number of unique sections: {len(section_counts)} (should be 4)")
print(f"All sections have equal counts: {len(set(section_counts)) == 1}\n")

# Test 3: Check we have all emotions represented
print("Number of unique emotions:", len(long_emotions_df['emotion'].unique()))
print("Emotions:", sorted(long_emotions_df['emotion'].unique()), "\n")

# Test 4: Compare values between original and long format
# Pick a random section and emotion to check
section = 'aspen'
emotion = 'happy'

# Get values from original dataframe
original_values = combined_emotions_df[
    (combined_emotions_df['section'] == section)
][emotion].values

# Get values from long format
long_values = long_emotions_df[
    (long_emotions_df['section'] == section) & 
    (long_emotions_df['emotion'] == emotion)
]['response'].values

print(f"Comparing values for {section} section, {emotion} emotion:")
print(f"Original values (first 5): {original_values[:5]}")
print(f"Long format values (first 5): {long_values[:5]}")
print(f"Values match: {(original_values == long_values).all()}\n")

# Test 5: Compare value counts across both dataframes
print("Comparing total response distributions:")
original_value_counts = combined_emotions_df[emotion].value_counts()
long_value_counts = long_emotions_df[
    long_emotions_df['emotion'] == emotion
]['response'].value_counts()
print(f"\nValue counts for '{emotion}':")
print("Original format:")
print(original_value_counts)
print("\nLong format:")
print(long_value_counts)
print(f"Distributions match: {original_value_counts.equals(long_value_counts)}\n")

# Test 6: Check for any null values
print("Null values in each column:")
print(long_emotions_df.isnull().sum())

# Test 7: Compare unique values without sorting
original_unique = set()
for col in combined_emotions_df.columns.drop('section'):
    original_unique.update(combined_emotions_df[col].unique())

long_unique = set(long_emotions_df['response'].unique())

print("\nUnique response values match:", original_unique == long_unique)
print("Original unique values:", list(original_unique))
print("Long format unique values:", list(long_unique))

Expected rows: 9724
Actual rows: 9724
Match: True

Sections and their counts:
section
aspen               2431
here_now_impacts    2431
build_momentum      2431
connecting          2431
Name: count, dtype: int64
Number of unique sections: 4 (should be 4)
All sections have equal counts: True

Number of unique emotions: 13
Emotions: ['afraid_scared', 'angry_frustrated', 'anxious', 'guilty', 'happy', 'hopeless', 'indifferent', 'inspired', 'interested', 'numb', 'optimistic_hopeful', 'sad', 'stressed']

Comparing values for aspen section, happy emotion:
Original values (first 5): ['Only a little' 'Only a little' 'A moderate amount' 'Only a little'
 'Not at all']
Long format values (first 5): ['Only a little' 'Only a little' 'A moderate amount' 'Only a little'
 'Not at all']
Values match: False

Comparing total response distributions:

Value counts for 'happy':
Original format:
happy
Not at all           216
Only a little        214
A moderate amount    213
A great deal          93
Name: count, dtype: int64

Long format:
response
Not at all           216
Only a little        214
A moderate amount    213
A great deal          93
Name: count, dtype: int64
Distributions match: True

Null values in each column:
section       0
emotion       0
response    157
dtype: int64

Unique response values match: True
Original unique values: ['Not at all', 'A moderate amount', 'A great deal', 'Only a little', nan]
Long format unique values: ['Not at all', 'A moderate amount', 'A great deal', 'Only a little', nan]

In [18]:
# Debugging comparison
section = 'aspen'
emotion = 'happy'

# Get values from both formats
original_values = combined_emotions_df[
    (combined_emotions_df['section'] == section)
][emotion].values

long_values = long_emotions_df[
    (long_emotions_df['section'] == section) & 
    (long_emotions_df['emotion'] == emotion)
]['response'].values

# Print detailed information
print("Detailed comparison:")
print(f"Length of original values: {len(original_values)}")
print(f"Length of long values: {len(long_values)}")
print("\nData types:")
print(f"Original values dtype: {original_values.dtype}")
print(f"Long values dtype: {long_values.dtype}")

# Compare first few values with type information
print("\nFirst 5 values with types:")
for i in range(5):
    orig = original_values[i]
    long = long_values[i]
    print(f"\nIndex {i}:")
    print(f"Original: {repr(orig)} (type: {type(orig)})")
    print(f"Long: {repr(long)} (type: {type(long)})")
    print(f"Equal?: {orig == long}")

Detailed comparison:
Length of original values: 187
Length of long values: 187

Data types:
Original values dtype: object
Long values dtype: object

First 5 values with types:

Index 0:
Original: 'Only a little' (type: <class 'str'>)
Long: 'Only a little' (type: <class 'str'>)
Equal?: True

Index 1:
Original: 'Only a little' (type: <class 'str'>)
Long: 'Only a little' (type: <class 'str'>)
Equal?: True

Index 2:
Original: 'A moderate amount' (type: <class 'str'>)
Long: 'A moderate amount' (type: <class 'str'>)
Equal?: True

Index 3:
Original: 'Only a little' (type: <class 'str'>)
Long: 'Only a little' (type: <class 'str'>)
Equal?: True

Index 4:
Original: 'Not at all' (type: <class 'str'>)
Long: 'Not at all' (type: <class 'str'>)
Equal?: True

In [15]:
long_emotions_df.to_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/combined_emotions_df_long_format.xlsx', index=False)