In [2]:
#IMPORTS
import pandas as pd

In [13]:
full_analysis_df = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_emotions_renamed.xlsx')
participant_index = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/Content_logs_participant_index_2_cleanIDs.xlsx')
display(participant_index)

,Researcher,Group,ida,Pseudonym,Age,Gender,Race,Zipcode,SASSY,Knowledge of CC,CC Conversations,CC engagement,Link (url),Who is in this video?,Notes,link (url),Analytic memo,NA
0,Lynne,24012401,24012401MG,Andy,23.0,Male,white,30338,Cautious,A moderate amount,1-2 times a month,.,https://uofu.app.box.com/file/1426588329322,"Andy (chest harness), Jason (red north face sh...","Camera died a few times, so video is sporadic",https://uofu.app.box.com/file/1439606960631,https://uofu.app.box.com/file/1446720926393,NaN
1,Lynne,24012401,24012401BF,Jason,23.0,Male,white,34786,Alarmed,A moderate amount,About once a week,.,NaN,NaN,NaN,NaN,NaN,NaN
2,Lynne,24012401,24012401PM,Sean,22.0,Male,white,75503,Alarmed,A moderate amount,1-2 times a month,.,NaN,NaN,NaN,NaN,NaN,NaN
3,Ben,24012601,24012601LS,Dorthy,63.0,Female,white,84074,Concerned,A moderate amount,About once a week,.,https://uofu.box.com/s/nzdxzxxz43exlgsgaxjthv8...,"Bill ( neck camera, blue flannel-type shirt, b...",Videos are similar. Dorthy's Content Log inclu...,https://uofu.box.com/s/bywwreoukb96dyr592ktbwz...,https://uofu.box.com/s/zq4tjr7lojtgxdtgb1yqrpv...,NaN
4,Ben,24012601,24012601RS,Bill,59.0,Male,white,84074,Doubtful,Only a little,1-2 times a month,.,https://uofu.box.com/s/pstrq6au0junb5f0w5qgv6m...,"Dorthy (neck camera, white fleece pullover)",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Jordan,240406_11,24040611KS,Lindsay,20.0,Female,Caucasian,84128,Alarmed,Only a little,1-2 times a month,A moderate amount,https://uofu.box.com/s/d7n4q6nvw1f6nfd2sdi983c...,Lindsay (camera around neck) \nSarah (grey swe...,NaN,NaN,NaN,NaN
158,NaN,240406_12,24040612JC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,NaN,240406_12,24040612WC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,NaN,240406_12,24040612LR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,NaN,240406_12,24040612KC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Fix incorrect ida values
full_analysis_df['ida'] = full_analysis_df['ida'].replace({
    '24030804GN': '24030904GN',
    '24030804AB': '24030904AB',
    '24030806JJ': '24030906JJ',
    '24030801KW': '24030901KW',
    '24030801SW': '24030901SW',
    '24040607EB': '24040607EO'
})

participant_index['ida'] = participant_index['ida'].replace({
    '24030101EN': '24030101EM'
})

In [15]:
# Merge the SASSY column from participant_index into full_analysis_df
# Using outer merge to keep all rows from both dataframes
full_analysis_df = full_analysis_df.merge(
    participant_index[['ida', 'SASSY']], 
    how='outer',
    left_on='ida',
    right_on='ida'
)

display(full_analysis_df)

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7,SASSY
0,2024-01-24 16:52:41,2024-01-24 19:29:43,IP Address,155.98.131.0,100.0,9422.0,True,2024-01-24 19:29:44,R_7JjAHZBazmS3x73,NaN,...,A little bit,Not at all,Moderately,Moderately,A little bit,A little bit,A little bit,A little bit,Not at all,Alarmed
1,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100.0,10464.0,True,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all,Cautious
2,2024-01-24 16:36:52,2024-01-24 19:30:16,IP Address,155.98.131.4,100.0,10404.0,True,2024-01-24 19:30:17,R_6wQQHroz2FD6m6G,NaN,...,A lot,Not at all,A little bit,Not at all,A little bit,Not at all,Moderately,A little bit,A lot,Alarmed
3,2024-01-24 19:30:11,2024-01-26 15:17:30,IP Address,155.98.131.2,100.0,157638.0,True,2024-01-26 15:17:31,R_6PO33vlaXgyLTdn,NaN,...,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,A little bit,A great deal,Concerned
4,2024-01-24 19:30:17,2024-01-26 15:20:15,IP Address,155.98.131.4,100.0,157797.0,True,2024-01-26 15:20:16,R_6rvUHTQiMej0h1A,NaN,...,Not at all,Not at all,A lot,Moderately,Moderately,A little bit,Not at all,Not at all,Not at all,Doubtful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2024-04-06 15:11:50,2024-04-06 16:08:12,IP Address,155.98.131.1,100.0,3382.0,True,2024-04-06 16:08:13,R_5zHgVIAkjwVgZIh,NaN,...,Not at all,Not at all,A little bit,A little bit,Not at all,Not at all,Not at all,Not at all,Not at all,Cautious
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Get the list of columns
cols = full_analysis_df.columns.tolist()

# Find the index of SASSY and sassy_q1
sassy_idx = cols.index('SASSY')
sassy_q1_idx = cols.index('sassy_q1')

# Remove SASSY from current position and insert before sassy_q1
cols.pop(sassy_idx)
cols.insert(sassy_q1_idx, 'SASSY')

# Reorder the dataframe columns
full_analysis_df = full_analysis_df[cols]