In [1]:
#IMPORTS
import pandas as pd

In [85]:
# full_analysis_df = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_emotions_renamed.xlsx')
# participant_index = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/Content_logs_participant_index_2_cleanIDs.xlsx')
full_analysis_df = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_emotions_renamed.xlsx')
participant_index = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/Content_logs_participant_index_2_cleanIDs.xlsx')

display(participant_index)

,Researcher,Group,ida,Pseudonym,Age,Gender,Race,Zipcode,SASSY,Knowledge of CC,CC Conversations,CC engagement,Link (url),Who is in this video?,Notes,link (url),Analytic memo,NA
0,Lynne,24012401,24012401MG,Andy,23.0,Male,white,30338,Cautious,A moderate amount,1-2 times a month,.,https://uofu.app.box.com/file/1426588329322,"Andy (chest harness), Jason (red north face sh...","Camera died a few times, so video is sporadic",https://uofu.app.box.com/file/1439606960631,https://uofu.app.box.com/file/1446720926393,NaN
1,Lynne,24012401,24012401BF,Jason,23.0,Male,white,34786,Alarmed,A moderate amount,About once a week,.,NaN,NaN,NaN,NaN,NaN,NaN
2,Lynne,24012401,24012401PM,Sean,22.0,Male,white,75503,Alarmed,A moderate amount,1-2 times a month,.,NaN,NaN,NaN,NaN,NaN,NaN
3,Ben,24012601,24012601LS,Dorthy,63.0,Female,white,84074,Concerned,A moderate amount,About once a week,.,https://uofu.box.com/s/nzdxzxxz43exlgsgaxjthv8...,"Bill ( neck camera, blue flannel-type shirt, b...",Videos are similar. Dorthy's Content Log inclu...,https://uofu.box.com/s/bywwreoukb96dyr592ktbwz...,https://uofu.box.com/s/zq4tjr7lojtgxdtgb1yqrpv...,NaN
4,Ben,24012601,24012601RS,Bill,59.0,Male,white,84074,Doubtful,Only a little,1-2 times a month,.,https://uofu.box.com/s/pstrq6au0junb5f0w5qgv6m...,"Dorthy (neck camera, white fleece pullover)",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Jordan,240406_11,24040611KS,Lindsay,20.0,Female,Caucasian,84128,Alarmed,Only a little,1-2 times a month,A moderate amount,https://uofu.box.com/s/d7n4q6nvw1f6nfd2sdi983c...,Lindsay (camera around neck) \nSarah (grey swe...,NaN,NaN,NaN,NaN
158,NaN,240406_12,24040612JC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,NaN,240406_12,24040612WC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,NaN,240406_12,24040612LR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,NaN,240406_12,24040612KC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
# Fix incorrect ida values
participant_index['ida'] = participant_index['ida'].replace({
    '24030101EN': '24030101EM'
})

#Clean SASSY values
participant_index['SASSY'] = participant_index['SASSY'].replace('.', pd.NA)
participant_index['SASSY'] = participant_index['SASSY'].str.strip()

In [87]:
# Merge the SASSY column from participant_index into full_analysis_df
# Using outer merge to keep all rows from both dataframes
full_analysis_df = full_analysis_df.merge(
    participant_index[['ida', 'SASSY']], 
    how='outer',
    left_on='ida',
    right_on='ida'
)

display(full_analysis_df)

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7,SASSY
0,2024-01-24 16:52:41,2024-01-24 19:29:43,IP Address,155.98.131.0,100.0,9422.0,True,2024-01-24 19:29:44,R_7JjAHZBazmS3x73,NaN,...,A little bit,Not at all,Moderately,Moderately,A little bit,A little bit,A little bit,A little bit,Not at all,Alarmed
1,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100.0,10464.0,True,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all,Cautious
2,2024-01-24 16:36:52,2024-01-24 19:30:16,IP Address,155.98.131.4,100.0,10404.0,True,2024-01-24 19:30:17,R_6wQQHroz2FD6m6G,NaN,...,A lot,Not at all,A little bit,Not at all,A little bit,Not at all,Moderately,A little bit,A lot,Alarmed
3,2024-01-24 19:30:11,2024-01-26 15:17:30,IP Address,155.98.131.2,100.0,157638.0,True,2024-01-26 15:17:31,R_6PO33vlaXgyLTdn,NaN,...,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,A little bit,A great deal,Concerned
4,2024-01-24 19:30:17,2024-01-26 15:20:15,IP Address,155.98.131.4,100.0,157797.0,True,2024-01-26 15:20:16,R_6rvUHTQiMej0h1A,NaN,...,Not at all,Not at all,A lot,Moderately,Moderately,A little bit,Not at all,Not at all,Not at all,Doubtful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2024-04-06 15:11:50,2024-04-06 16:08:12,IP Address,155.98.131.1,100.0,3382.0,True,2024-04-06 16:08:13,R_5zHgVIAkjwVgZIh,NaN,...,Not at all,Not at all,A little bit,A little bit,Not at all,Not at all,Not at all,Not at all,Not at all,Cautious
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
# Get the list of columns
cols = full_analysis_df.columns.tolist()

# Find the index of SASSY and sassy_q1
sassy_idx = cols.index('SASSY')
sassy_q1_idx = cols.index('sassy_q1')

# Remove SASSY from current position and insert before sassy_q1
cols.pop(sassy_idx)
cols.insert(sassy_q1_idx, 'SASSY')

# Reorder the dataframe columns
full_analysis_df = full_analysis_df[cols]

In [89]:
missing_sassy_df = pd.read_csv('c:/Users/u1172791/COH files/Data_2025/MissingSASSY_Hartland Segmentation.csv')
display(missing_sassy_df)

,ida,important,worry,personal,future,SASSY
0,24022302RL,Very important,Very worried,A moderate amount,A great deal,Alarmed
1,24022401BB,Extremely important,Somewhat worried,A great deal,A great deal,Alarmed
2,24022401LV,Somewhat important,Not very worried,Only a little,A great deal,Concerned
3,24022401YG,Very important,Somewhat worried,A moderate amount,A great deal,Concerned
4,24022401ZG,Somewhat important,Somewhat worried,A moderate amount,A great deal,Concerned
5,24022403MA,Somewhat important,Not very worried,Not at all,Only a little,Doubtful
6,24022403OA,Very important,Somewhat worried,A moderate amount,A great deal,Concerned
7,24022409DH,Extremely important,Very worried,A great deal,A great deal,Alarmed
8,24022409SM,Very important,Somewhat worried,A moderate amount,A great deal,Concerned
9,24022409SMDAUGHTER13,Very important,Somewhat worried,A moderate amount,A great deal,Concerned
10,24022410AF,Very important,Very worried,A great deal,A great deal,Alarmed
11,24022410SF,Very important,Very worried,A great deal,A great deal,Alarmed
12,24022411SDR,Very important,Very worried,A great deal,A great deal,Alarmed
13,24022413EH,Extremely important,Very worried,A moderate amount,A great deal,Alarmed
14,24022417CA,Very important,Somewhat worried,A great deal,A great deal,Alarmed
15,24022419AF,Very important,Somewhat worried,A great deal,A moderate amount,Concerned
16,24022419IF,Very important,Somewhat worried,A great deal,A moderate amount,Concerned
17,24022419CF,Somewhat important,Not at all worried,Only a little,Only a little,Doubtful
18,24032301CH,Very important,Not very worried,A moderate amount,A great deal,Concerned
19,24032301MH,Extremely important,Very worried,A great deal,A great deal,Alarmed
20,24032302KK,Somewhat important,Somewhat worried,A great deal,A great deal,Concerned
21,24032302MC,Extremely important,Somewhat worried,A great deal,A great deal,Alarmed
22,24032303TL,Very important,Somewhat worried,A moderate amount,A great deal,Concerned
23,24032304YDSON,Very important,Somewhat worried,A moderate amount,A great deal,Concerned
24,24032305U,Extremely important,Very worried,A moderate amount,A great deal,Alarmed

In [90]:
# Update SASSY scores in full_analysis_df with values from missing_sassy_df
full_analysis_df = full_analysis_df.merge(
    missing_sassy_df[['ida', 'SASSY']], 
    how='left',
    on='ida',
    suffixes=('', '_new')
)

# Where SASSY is NaN, use the new value from missing_sassy_df
full_analysis_df['SASSY'] = full_analysis_df['SASSY'].fillna(full_analysis_df['SASSY_new'])

# Drop the temporary column
full_analysis_df = full_analysis_df.drop('SASSY_new', axis=1)
display(full_analysis_df)

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_48,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7
0,2024-01-24 16:52:41,2024-01-24 19:29:43,IP Address,155.98.131.0,100.0,9422.0,True,2024-01-24 19:29:44,R_7JjAHZBazmS3x73,NaN,...,A little bit,A little bit,Not at all,Moderately,Moderately,A little bit,A little bit,A little bit,A little bit,Not at all
1,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100.0,10464.0,True,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,A lot,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all
2,2024-01-24 16:36:52,2024-01-24 19:30:16,IP Address,155.98.131.4,100.0,10404.0,True,2024-01-24 19:30:17,R_6wQQHroz2FD6m6G,NaN,...,Moderately,A lot,Not at all,A little bit,Not at all,A little bit,Not at all,Moderately,A little bit,A lot
3,2024-01-24 19:30:11,2024-01-26 15:17:30,IP Address,155.98.131.2,100.0,157638.0,True,2024-01-26 15:17:31,R_6PO33vlaXgyLTdn,NaN,...,Extremely,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,A little bit,A great deal
4,2024-01-24 19:30:17,2024-01-26 15:20:15,IP Address,155.98.131.4,100.0,157797.0,True,2024-01-26 15:20:16,R_6rvUHTQiMej0h1A,NaN,...,Not at all,Not at all,Not at all,A lot,Moderately,Moderately,A little bit,Not at all,Not at all,Not at all
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2024-04-06 15:11:50,2024-04-06 16:08:12,IP Address,155.98.131.1,100.0,3382.0,True,2024-04-06 16:08:13,R_5zHgVIAkjwVgZIh,NaN,...,Moderately,Not at all,Not at all,A little bit,A little bit,Not at all,Not at all,Not at all,Not at all,Not at all
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
all_doors_by_person_exhibit = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/side_doors_by_person_and_exhibit.xlsx')
#all_doors_by_person_exhibit = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/side_doors_by_person_and_exhibit.xlsx')
display(all_doors_by_person_exhibit)

,Pseudonym,Group ID,Group Type,age,gender,race,zip,SASSY,UT?,rural/urban,...,Exhibit #_13_mm,Exhibit #_15_mm,Exhibit #_general_mm,Exhibit #_s3_mm,Exhibit #_1_mm,Exhibit #_8_mm,Exhibit #_14_mm,Exhibit #_s1_mm,Exhibit #_s2_mm,Exhibit #_s4_mm
0,Alex,24040505,AC,35,Male,Black or African American,47904,Alarmed,0,3,...,0,0,0,0,0,0,0,0,0,0
1,Allie,240313_04,Mixed,28,Female,Caucasian,84401,Concerned,1,2,...,0,0,0,0,0,0,0,0,0,0
2,Amy,24040302,CC,20,Female,Caucasian,84095,Cautious,1,1,...,0,0,0,0,0,0,0,0,0,0
3,Andy,24012401,mixed,23,Male,white,30338,Cautious,0,1,...,0,0,0,0,0,0,0,0,0,0
4,Asher,24.02.23_02,Mixed Group,17,Male,Caucasian,R3K0B4,Cautious,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Tam,240313_02,Mixed,28,Male,Asian,Winnipeg,Cautious,0,0,...,0,0,0,0,0,0,0,0,0,0
72,Ted,24040608,AC,29,Male,"Other, please specify",84119,Alarmed,1,1,...,0,0,0,1,0,0,0,0,0,0
73,Terry,24030804,AC,20,Male,Caucasian,59725,Concerned,0,9,...,0,0,0,0,0,0,0,0,0,0
74,Tim,24020903,AC,37,Male,Asian,98264,Alarmed,0,3,...,0,0,0,0,0,0,0,0,0,0
75,Tina,240309_06,mixed,14,female,Caucasian,84044,NaN,1,1,...,0,0,0,0,0,0,0,0,0,0

In [92]:
# Fix misspellings in participant index
participant_index.loc[participant_index['Pseudonym'] == 'Dorthy', 'Pseudonym'] = 'Dorothy'
participant_index.loc[participant_index['Pseudonym'] == 'Deitze', 'Pseudonym'] = 'Dietze'
# Strip whitespace from Pseudonym column
participant_index['Pseudonym'] = participant_index['Pseudonym'].str.strip()

In [93]:

# Merge Pseudonym from participant index into full analysis dataframe
full_analysis_df = full_analysis_df.merge(
    participant_index[['ida', 'Pseudonym']],
    how='outer', 
    on='ida'
)

In [94]:
# Merge U? and rural/urban columns from all_doors_by_person_exhibit into full analysis dataframe
full_analysis_df = full_analysis_df.merge(
    all_doors_by_person_exhibit[['Pseudonym', 'UT?', 'rural/urban']],
    how='outer',
    on='Pseudonym'
)

In [95]:
# Get list of columns
cols = full_analysis_df.columns.tolist()

# Remove columns we want to reposition
cols.remove('Pseudonym')
cols.remove('UT?')
cols.remove('rural/urban')

# Get index of reference columns
ida_idx = cols.index('ida')
zipcode_idx = cols.index('zipcode')

# Insert columns in desired positions
cols.insert(ida_idx + 1, 'Pseudonym')
cols.insert(zipcode_idx + 2, 'UT?')
cols.insert(zipcode_idx + 3, 'rural/urban')

# Reorder columns
full_analysis_df = full_analysis_df[cols]

In [96]:
#full_analysis_df.to_excel('c:/Users/u1172791/COH files/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_w_SASSY_scores.xlsx', index=False)

In [5]:
#full_w_urban_codes = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_w_SASSY_urban_rural.xlsx')
full_w_urban_codes = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_w_SASSY_urban_rural.xlsx')

In [3]:
#Clean SASSY values
full_w_urban_codes['SASSY'] = full_w_urban_codes['SASSY'].replace('.', pd.NA)
full_w_urban_codes['SASSY'] = full_w_urban_codes['SASSY'].str.strip()

In [6]:
#full_w_urban_codes.to_excel('c:/Users/u1172791/COH files/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_w_SASSY_urban_rural.xlsx')
full_w_urban_codes.to_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_w_SASSY_urban_rural.xlsx', index = False)

In [98]:
#not finished - merge urban codes into participant index
participant_index = participant_index.merge(
    full_w_urban_codes[['ida', 'UT?', 'rural/urban']],
    how='left', 
    on='ida'
)