In [11]:
#IMPORTS

import pandas as pd

In [12]:
full_analysis_df = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_emotions_renamed.xlsx')
#full_analysis_df = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_emotions_renamed.xlsx')
display(full_analysis_df)

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_48,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7
0,2024-01-24 16:52:41,2024-01-24 19:29:43,IP Address,155.98.131.0,100,9422,True,2024-01-24 19:29:44,R_7JjAHZBazmS3x73,NaN,...,A little bit,A little bit,Not at all,Moderately,Moderately,A little bit,A little bit,A little bit,A little bit,Not at all
1,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100,10464,True,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,A lot,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all
2,2024-01-24 16:36:52,2024-01-24 19:30:16,IP Address,155.98.131.4,100,10404,True,2024-01-24 19:30:17,R_6wQQHroz2FD6m6G,NaN,...,Moderately,A lot,Not at all,A little bit,Not at all,A little bit,Not at all,Moderately,A little bit,A lot
3,2024-01-24 19:30:11,2024-01-26 15:17:30,IP Address,155.98.131.2,100,157638,True,2024-01-26 15:17:31,R_6PO33vlaXgyLTdn,NaN,...,Extremely,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,A little bit,A great deal
4,2024-01-24 19:30:17,2024-01-26 15:20:15,IP Address,155.98.131.4,100,157797,True,2024-01-26 15:20:16,R_6rvUHTQiMej0h1A,NaN,...,Not at all,Not at all,Not at all,A lot,Moderately,Moderately,A little bit,Not at all,Not at all,Not at all
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,2024-04-06 14:36:07,2024-04-06 15:32:22,IP Address,155.98.131.0,100,3375,True,2024-04-06 15:32:23,R_62alnCFIpW4CjnZ,NaN,...,A little bit,A little bit,Not at all,A great deal,Moderately,A little bit,Not at all,Not at all,A little bit,Moderately
183,2024-04-06 14:35:16,2024-04-06 15:30:12,IP Address,155.98.131.7,100,3296,True,2024-04-06 15:30:13,R_3lv4Z5yPo0XEf9D,NaN,...,A little bit,Moderately,Not at all,A lot,A lot,A lot,A lot,Not at all,A lot,A great deal
184,2024-04-06 14:34:46,2024-04-06 15:31:05,IP Address,155.98.131.5,100,3378,True,2024-04-06 15:31:05,R_3fNzlkOukIhRV9V,NaN,...,Not at all,Moderately,Not at all,A great deal,A great deal,A great deal,A great deal,A little bit,A great deal,A great deal
185,2024-04-06 13:48:14,2024-04-06 16:11:15,IP Address,155.98.131.3,100,8581,True,2024-04-06 16:11:16,R_60pdvn9w8Nkf2se,NaN,...,A lot,Not at all,Not at all,A little bit,A little bit,Not at all,A little bit,A little bit,A little bit,Moderately
186,2024-04-06 15:11:50,2024-04-06 16:08:12,IP Address,155.98.131.1,100,3382,True,2024-04-06 16:08:13,R_5zHgVIAkjwVgZIh,NaN,...,Moderately,Not at all,Not at all,A little bit,A little bit,Not at all,Not at all,Not at all,Not at all,Not at all

In [13]:
# Define the prefixes we're looking for
emotion_prefixes = ['aspen_', 'here_now_impacts_', 'build_momentum_', 'connecting_']

# Define mapping dictionary for converting text responses to numeric values
response_map = {
    'Not at all': 0,
    'Only a little': 1,
    'A moderate amount': 2,
    'A great deal': 3
}

# Get all columns that start with any of these prefixes
emotion_columns = [col for col in full_analysis_df.columns 
                  if any(col.startswith(prefix) for prefix in emotion_prefixes)]

# Convert emotion columns using the mapping
for col in emotion_columns:
    full_analysis_df[col] = full_analysis_df[col].map(response_map)

# Verify the conversion worked by showing unique values in the emotion columns
print("\nUnique values in emotion columns after conversion:")
for col in emotion_columns:
    print(f"\n{col}:")
    print(full_analysis_df[col].unique())

# Display the updated dataframe
display(full_analysis_df)

Unique values in emotion columns after conversion:

aspen_indifferent:
[ 1.  0.  2.  3. nan]

aspen_sad:
[ 0.  1.  2.  3. nan]

aspen_hopeless:
[ 0.  2.  1.  3. nan]

aspen_interested:
[ 1.  2.  3.  0. nan]

aspen_afraid_scared:
[ 1.  0.  2.  3. nan]

aspen_optimistic_hopeful:
[ 2.  1.  3.  0. nan]

aspen_anxious:
[ 1.  0.  2.  3. nan]

aspen_inspired:
[ 1.  2.  0.  3. nan]

aspen_angry_frustrated:
[ 0.  2.  3.  1. nan]

aspen_happy:
[ 1.  2.  0.  3. nan]

aspen_guilty:
[ 0.  1.  2.  3. nan]

aspen_numb:
[ 0.  2.  1. nan  3.]

aspen_stressed:
[ 1.  0.  2. nan  3.]

here_now_impacts_indifferent:
[ 0.  1.  2. nan  3.]

here_now_impacts_sad:
[ 2.  1.  0.  3. nan]

here_now_impacts_hopeless:
[ 1.  0.  2.  3. nan]

here_now_impacts_interested:
[ 2.  1.  3.  0. nan]

here_now_impacts_afraid_scared:
[ 2.  0.  1.  3. nan]

here_now_impacts_optimistic_hopeful:
[ 1.  2.  0.  3. nan]

here_now_impacts_anxious:
[ 2.  1.  0.  3. nan]

here_now_impacts_inspired:
[ 1.  0.  2.  3. nan]

here_now_impacts_angry_frustrated:
[ 1.  0.  2.  3. nan]

here_now_impacts_happy:
[ 0.  2.  1.  3. nan]

here_now_impacts_guilty:
[ 2.  0.  1.  3. nan]

here_now_impacts_numb:
[ 0.  1.  2.  3. nan]

here_now_impacts_stressed:
[ 2.  0.  1.  3. nan]

build_momentum_indifferent:
[ 0.  1.  2. nan  3.]

build_momentum_sad:
[ 1.  0.  2. nan  3.]

build_momentum_hopeless:
[ 0.  1.  2. nan  3.]

build_momentum_interested:
[ 2.  3.  1.  0. nan]

build_momentum_afraid_scared:
[ 1.  0.  2.  3. nan]

build_momentum_optimistic_hopeful:
[ 1.  2.  0.  3. nan]

build_momentum_anxious:
[ 1.  0.  2. nan  3.]

build_momentum_inspired:
[ 1.  0.  2.  3. nan]

build_momentum_angry_frustrated:
[ 2.  1.  0.  3. nan]

build_momentum_happy:
[ 1.  0.  2.  3. nan]

build_momentum_guilty:
[ 0.  1.  2.  3. nan]

build_momentum_numb:
[ 0.  2.  1.  3. nan]

build_momentum_stressed:
[ 0.  1.  2.  3. nan]

connecting_indifferent:
[ 0.  1.  3.  2. nan]

connecting_sad:
[ 0.  1.  2. nan  3.]

connecting_hopeless:
[ 0.  1.  3.  2. nan]

connecting_interested:
[ 1.  2.  3.  0. nan]

connecting_afraid_scared:
[ 0.  1.  2. nan  3.]

connecting_optimistic_hopeful:
[ 1.  3.  2.  0. nan]

connecting_anxious:
[ 0.  1.  2. nan  3.]

connecting_inspired:
[ 1.  2.  0.  3. nan]

connecting_angry_frustrated:
[ 0.  2.  1.  3. nan]

connecting_happy:
[ 1.  0.  2.  3. nan]

connecting_guilty:
[ 0.  1.  2.  3. nan]

connecting_numb:
[ 0.  1.  2. nan  3.]

connecting_stressed:
[ 0.  1.  2.  3. nan]

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_48,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7
0,2024-01-24 16:52:41,2024-01-24 19:29:43,IP Address,155.98.131.0,100,9422,True,2024-01-24 19:29:44,R_7JjAHZBazmS3x73,NaN,...,A little bit,A little bit,Not at all,Moderately,Moderately,A little bit,A little bit,A little bit,A little bit,Not at all
1,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100,10464,True,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,A lot,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all
2,2024-01-24 16:36:52,2024-01-24 19:30:16,IP Address,155.98.131.4,100,10404,True,2024-01-24 19:30:17,R_6wQQHroz2FD6m6G,NaN,...,Moderately,A lot,Not at all,A little bit,Not at all,A little bit,Not at all,Moderately,A little bit,A lot
3,2024-01-24 19:30:11,2024-01-26 15:17:30,IP Address,155.98.131.2,100,157638,True,2024-01-26 15:17:31,R_6PO33vlaXgyLTdn,NaN,...,Extremely,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,A little bit,A great deal
4,2024-01-24 19:30:17,2024-01-26 15:20:15,IP Address,155.98.131.4,100,157797,True,2024-01-26 15:20:16,R_6rvUHTQiMej0h1A,NaN,...,Not at all,Not at all,Not at all,A lot,Moderately,Moderately,A little bit,Not at all,Not at all,Not at all
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,2024-04-06 14:36:07,2024-04-06 15:32:22,IP Address,155.98.131.0,100,3375,True,2024-04-06 15:32:23,R_62alnCFIpW4CjnZ,NaN,...,A little bit,A little bit,Not at all,A great deal,Moderately,A little bit,Not at all,Not at all,A little bit,Moderately
183,2024-04-06 14:35:16,2024-04-06 15:30:12,IP Address,155.98.131.7,100,3296,True,2024-04-06 15:30:13,R_3lv4Z5yPo0XEf9D,NaN,...,A little bit,Moderately,Not at all,A lot,A lot,A lot,A lot,Not at all,A lot,A great deal
184,2024-04-06 14:34:46,2024-04-06 15:31:05,IP Address,155.98.131.5,100,3378,True,2024-04-06 15:31:05,R_3fNzlkOukIhRV9V,NaN,...,Not at all,Moderately,Not at all,A great deal,A great deal,A great deal,A great deal,A little bit,A great deal,A great deal
185,2024-04-06 13:48:14,2024-04-06 16:11:15,IP Address,155.98.131.3,100,8581,True,2024-04-06 16:11:16,R_60pdvn9w8Nkf2se,NaN,...,A lot,Not at all,Not at all,A little bit,A little bit,Not at all,A little bit,A little bit,A little bit,Moderately
186,2024-04-06 15:11:50,2024-04-06 16:08:12,IP Address,155.98.131.1,100,3382,True,2024-04-06 16:08:13,R_5zHgVIAkjwVgZIh,NaN,...,Moderately,Not at all,Not at all,A little bit,A little bit,Not at all,Not at all,Not at all,Not at all,Not at all

In [14]:
# Calculate medians for all emotion columns
emotion_medians = full_analysis_df[emotion_columns].median()

# Display the medians
print("\nMedians for emotion columns:")
print(emotion_medians)

Medians for emotion columns:
aspen_indifferent                      0.0
aspen_sad                              1.0
aspen_hopeless                         0.0
aspen_interested                       2.0
aspen_afraid_scared                    0.0
aspen_optimistic_hopeful               2.0
aspen_anxious                          1.0
aspen_inspired                         1.0
aspen_angry_frustrated                 0.0
aspen_happy                            2.0
aspen_guilty                           0.0
aspen_numb                             0.0
aspen_stressed                         0.0
here_now_impacts_indifferent           0.0
here_now_impacts_sad                   1.0
here_now_impacts_hopeless              1.0
here_now_impacts_interested            2.0
here_now_impacts_afraid_scared         1.0
here_now_impacts_optimistic_hopeful    1.0
here_now_impacts_anxious               1.0
here_now_impacts_inspired              1.0
here_now_impacts_angry_frustrated      1.0
here_now_impacts_happy                 0.0
here_now_impacts_guilty                1.0
here_now_impacts_numb                  0.0
here_now_impacts_stressed              1.0
build_momentum_indifferent             0.0
build_momentum_sad                     0.0
build_momentum_hopeless                0.0
build_momentum_interested              2.0
build_momentum_afraid_scared           0.0
build_momentum_optimistic_hopeful      2.0
build_momentum_anxious                 0.0
build_momentum_inspired                2.0
build_momentum_angry_frustrated        0.0
build_momentum_happy                   1.0
build_momentum_guilty                  0.0
build_momentum_numb                    0.0
build_momentum_stressed                0.0
connecting_indifferent                 0.0
connecting_sad                         0.0
connecting_hopeless                    0.0
connecting_interested                  2.0
connecting_afraid_scared               0.0
connecting_optimistic_hopeful          2.0
connecting_anxious                     0.0
connecting_inspired                    2.0
connecting_angry_frustrated            0.0
connecting_happy                       1.0
connecting_guilty                      0.0
connecting_numb                        0.0
connecting_stressed                    0.0
dtype: float64

In [15]:
emotion_means = full_analysis_df[emotion_columns].mean()

# Display the means
print("\nMeans for emotion columns:")
print(emotion_means)

Means for emotion columns:
aspen_indifferent                      0.652174
aspen_sad                              0.793478
aspen_hopeless                         0.668478
aspen_interested                       2.038043
aspen_afraid_scared                    0.641304
aspen_optimistic_hopeful               1.538043
aspen_anxious                          0.798913
aspen_inspired                         1.478261
aspen_angry_frustrated                 0.625000
aspen_happy                            1.619565
aspen_guilty                           0.625000
aspen_numb                             0.336957
aspen_stressed                         0.576087
here_now_impacts_indifferent           0.540984
here_now_impacts_sad                   1.413043
here_now_impacts_hopeless              1.054348
here_now_impacts_interested            2.190217
here_now_impacts_afraid_scared         1.135870
here_now_impacts_optimistic_hopeful    1.016304
here_now_impacts_anxious               1.114130
here_now_impacts_inspired              1.114130
here_now_impacts_angry_frustrated      1.201087
here_now_impacts_happy                 0.663043
here_now_impacts_guilty                0.820652
here_now_impacts_numb                  0.538043
here_now_impacts_stressed              1.103261
build_momentum_indifferent             0.581522
build_momentum_sad                     0.483696
build_momentum_hopeless                0.461957
build_momentum_interested              2.141304
build_momentum_afraid_scared           0.440217
build_momentum_optimistic_hopeful      1.717391
build_momentum_anxious                 0.532609
build_momentum_inspired                1.652174
build_momentum_angry_frustrated        0.570652
build_momentum_happy                   1.364130
build_momentum_guilty                  0.429348
build_momentum_numb                    0.282609
build_momentum_stressed                0.538043
connecting_indifferent                 0.641304
connecting_sad                         0.364130
connecting_hopeless                    0.369565
connecting_interested                  1.967391
connecting_afraid_scared               0.347826
connecting_optimistic_hopeful          1.663043
connecting_anxious                     0.505435
connecting_inspired                    1.619565
connecting_angry_frustrated            0.413043
connecting_happy                       1.347826
connecting_guilty                      0.418478
connecting_numb                        0.239130
connecting_stressed                    0.461957
dtype: float64

In [16]:
#emotions_by_section_numeric = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/emotions_by_section_df.xlsx')
emotions_by_section_numeric = pd.read_excel('c:/Users/u1172791/COH files/Data_2025/emotions_by_section_df.xlsx')


# Define the columns to convert (all columns except 'ida' and 'emotion')
columns_to_convert = [col for col in emotions_by_section_numeric.columns if col not in ['ida', 'emotion']]

# Convert the columns using the same response_map
for col in columns_to_convert:
    emotions_by_section_numeric[col] = emotions_by_section_numeric[col].map(response_map)

# Display the updated dataframe
print("\nConverted emotions by section dataframe:")
display(emotions_by_section_numeric)

Converted emotions by section dataframe:

,ida,emotion,aspen,here_now_impacts,build_momentum,connecting
0,24012401BF,indifferent,1.0,0.0,0.0,0.0
1,24012401BF,sad,0.0,2.0,1.0,0.0
2,24012401BF,hopeless,0.0,1.0,0.0,0.0
3,24012401BF,interested,1.0,2.0,2.0,1.0
4,24012401BF,afraid_scared,1.0,2.0,1.0,0.0
...,...,...,...,...,...,...
2426,24040611MM,angry_frustrated,3.0,3.0,2.0,1.0
2427,24040611MM,happy,1.0,0.0,0.0,1.0
2428,24040611MM,guilty,0.0,0.0,0.0,0.0
2429,24040611MM,numb,0.0,0.0,0.0,1.0
2430,24040611MM,stressed,0.0,0.0,1.0,1.0

In [17]:
# Create a new column 'mean_emotion_score' that averages all numeric columns
emotions_by_section_numeric['mean_emotion_score'] = emotions_by_section_numeric[columns_to_convert].mean(axis=1)

# Display the updated dataframe with the new column
print("\nEmotions by section dataframe with mean scores:")
display(emotions_by_section_numeric)

Emotions by section dataframe with mean scores:

,ida,emotion,aspen,here_now_impacts,build_momentum,connecting,mean_emotion_score
0,24012401BF,indifferent,1.0,0.0,0.0,0.0,0.25
1,24012401BF,sad,0.0,2.0,1.0,0.0,0.75
2,24012401BF,hopeless,0.0,1.0,0.0,0.0,0.25
3,24012401BF,interested,1.0,2.0,2.0,1.0,1.50
4,24012401BF,afraid_scared,1.0,2.0,1.0,0.0,1.00
...,...,...,...,...,...,...,...
2426,24040611MM,angry_frustrated,3.0,3.0,2.0,1.0,2.25
2427,24040611MM,happy,1.0,0.0,0.0,1.0,0.50
2428,24040611MM,guilty,0.0,0.0,0.0,0.0,0.00
2429,24040611MM,numb,0.0,0.0,0.0,1.0,0.25
2430,24040611MM,stressed,0.0,0.0,1.0,1.0,0.50

In [18]:
# Create a pivot table to get mean scores for each emotion by ida
emotions_mean_by_ida = emotions_by_section_numeric.pivot_table(
    index='ida',
    columns='emotion',
    values='mean_emotion_score',
    aggfunc='mean'
).reset_index()

# Display the resulting dataframe
print("\nMean emotion scores by ID:")
display(emotions_mean_by_ida)

Mean emotion scores by ID:

emotion,ida,afraid_scared,angry_frustrated,anxious,guilty,happy,hopeless,indifferent,inspired,interested,numb,optimistic_hopeful,sad,stressed
0,24012401BF,1.00,0.75,1.00,0.50,0.75,0.25,0.25,1.00,1.50,0.00,1.25,0.75,0.75
1,24012401MG,0.00,0.25,0.25,0.00,0.50,0.25,0.25,0.75,2.25,0.50,1.75,0.50,0.00
2,24012401PM,0.75,1.25,1.00,1.00,1.00,0.25,0.50,1.50,2.00,0.00,2.00,1.00,1.00
3,24012601LS,0.75,1.00,0.00,0.75,1.00,0.50,0.00,1.00,2.00,1.00,2.50,1.00,1.00
4,24012601RS,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,2.00,0.00,0.50,0.25,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,24040610EC,0.00,0.00,0.25,0.00,1.50,0.00,0.50,1.00,2.25,0.00,1.75,0.25,0.50
180,24040610MC,1.00,0.75,0.50,0.00,0.50,1.00,0.75,0.25,1.50,0.00,1.00,1.00,0.50
181,24040610OW,1.50,1.25,1.25,1.00,0.75,1.50,0.50,0.75,2.25,1.00,1.00,1.25,1.00
182,24040611KS,1.25,1.50,0.50,0.25,1.50,1.50,0.25,1.50,2.50,0.25,1.50,1.00,0.25
183,24040611MM,1.00,2.25,0.75,0.00,0.50,1.00,0.25,2.00,2.75,0.25,1.00,1.25,0.50

In [19]:
# Calculate means for each emotion column (excluding 'ida')
emotion_means = emotions_mean_by_ida.drop('ida', axis=1).mean()

# Print the means for each emotion
print("\nMean scores across all participants for each emotion:")
print(emotion_means)

Mean scores across all participants for each emotion:
emotion
afraid_scared         0.641304
angry_frustrated      0.702446
anxious               0.737772
guilty                0.573370
happy                 1.248641
hopeless              0.638587
indifferent           0.605978
inspired              1.466033
interested            2.084239
numb                  0.349185
optimistic_hopeful    1.483696
sad                   0.763587
stressed              0.669837
dtype: float64

In [21]:
emotions_mean_by_ida.to_excel('c:/Users/u1172791/COH files/Data_2025/emotion_means_by_id.xlsx', index=False)