In [1]:
#IMPORTS

import pandas as pd

In [3]:
full_analysis_df = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/COMBINED_TEXT_jan-june_pre_in-gallery_post_w_SASSY_urban_rural.xlsx')
display(full_analysis_df)

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_48,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7
0,2024-04-05 14:12:54,2024-04-05 15:57:31,IP Address,155.98.131.1,100.0,6276.0,1.0,2024-04-05 15:57:31,R_2dPUXEtypfBvZhD,NaN,...,A little bit,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,Moderately,A lot
1,2024-03-13 18:59:27,2024-03-13 20:15:18,IP Address,155.98.131.5,100.0,4550.0,1.0,2024-03-13 20:15:19,R_7PAooFY6nTwIqA7,NaN,...,A little bit,Not at all,Not at all,A great deal,A great deal,A great deal,Moderately,Not at all,Moderately,A lot
2,2024-03-23 13:49:19,2024-04-03 19:27:57,IP Address,155.98.131.5,100.0,970717.0,1.0,2024-04-03 19:27:58,R_73AteLV2ZE5L4GJ,NaN,...,A lot,Moderately,A lot,Moderately,A little bit,A little bit,A little bit,A little bit,Moderately,A little bit
3,2024-01-26 15:51:59,2024-01-26 16:41:06,IP Address,155.98.131.2,100.0,2946.0,1.0,2024-01-26 16:41:06,R_3uP2DqVWkGDu8La,NaN,...,Extremely,Moderately,Not at all,Moderately,A lot,A great deal,Moderately,A little bit,Moderately,Moderately
4,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100.0,10464.0,1.0,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,A lot,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2024-04-06 14:34:46,2024-04-06 15:31:05,IP Address,155.98.131.5,100.0,3378.0,1.0,2024-04-06 15:31:05,R_3fNzlkOukIhRV9V,NaN,...,Not at all,Moderately,Not at all,A great deal,A great deal,A great deal,A great deal,A little bit,A great deal,A great deal
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
hartland_participant_index = pd.read_excel('c:/Users/Hailey Sherman/ClimateOfHopeData/Data_2025/Content_logs_participant_index_hartland_cleanIDs.xlsx')
display(hartland_participant_index)

,Researcher,Group,ida,Pseudonym,Age,Gender,Race,Zipcode,SASSY,Knowledge of CC,CC Conversations,CC engagement,Link (url),Who is in this video?,Notes,link (url),Analytic memo,NA
0,NaN,24022401,24022401BB,Taylor,18.0,Genderqueer,"More than one race, please specify",84044.0,Alarmed,A moderate amount,About once a week,A moderate amount,https://uofu.app.box.com/file/1472564243462,Taylor (POV),NaN,NaN,NaN,NaN
1,NaN,24022401,24022401YG,Grant,14.0,Male,Prefer not to say,84118.0,Concerned,A moderate amount,1-2 times a month,A moderate amount,NaN,Grant young teenage boy wearing a blue button up,NaN,NaN,NaN,NaN
2,NaN,24022401,24022401LV,NaN,38.0,Female,Caucasian,84118.0,Concerned,Only a little,NaN,Only a little,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,24022401,24022401ZG,NaN,11.0,Female,"More than one race, please specify",84118.0,Concerned,A moderate amount,Not at all,Only a little,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,24022403,24022403OA,NaN,42.0,Male,"Other, please specify",84116.0,Concerned,A moderate amount,Not at all,Only a little,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,24022403,24022403MA,NaN,15.0,Female,"Other, please specify",84116.0,Doubtful,Only a little,Not at all,Not at all,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,24022409,24022409SM,NaN,25.0,Male,Caucasian,84116.0,Concerned,A moderate amount,1-2 times a month,Only a little,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,24022409,24022409DH,NaN,25.0,Female,"Other, please specify",84116.0,Alarmed,A great deal,1-2 times a month,A great deal,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,24022409,24022409SMDAUGHTER13,NaN,11.0,Female,Caucasian,84116.0,Concerned,A moderate amount,About once a week,A great deal,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,24022410,24022410AF,NaN,25.0,Female,Prefer not to say,84104.0,Alarmed,Only a little,1-2 times a month,A moderate amount,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,24022410,24022410SF,NaN,18.0,Female,Prefer not to say,84104.0,Alarmed,A moderate amount,About once a week,A moderate amount,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,240224_11,24022411SDR,NaN,35.0,Female,Prefer not to say,84119.0,Alarmed,Only a little,Not at all,A moderate amount,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,24022413,24022413EH,NaN,29.0,Female,Prefer not to say,84104.0,Alarmed,Only a little,Every day,A great deal,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,240224_17,24022417CA,NaN,33.0,Female,Prefer not to say,84104.0,Alarmed,A great deal,1-2 times a month,A moderate amount,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,240224_17,24022417CG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,240224_19,24022419AF,NaN,46.0,Female,"More than one race, please specify",84081.0,Concerned,A moderate amount,Not at all,Only a little,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,240224_19,24022419CF,NaN,11.0,Male,"Other, please specify",84081.0,Doubtful,Only a little,Not at all,Not at all,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,240224_19,24022419IF,NaN,14.0,Female,"More than one race, please specify",84081.0,Concerned,A moderate amount,1-2 times a month,Only a little,NaN,NaN,NaN,NaN,NaN,NaN
18,Indy,24032301,24032301MH,Margie,43.0,Female,Caucasian,84116.0,Alarmed,A great deal,1-2 times a month,A great deal,"https://uofu.app.box.com/file/1489627268956, h...","Margie (POV), Andre in brown sweater",NaN,https://uofu.app.box.com/file/1770839150076,https://uofu.app.box.com/file/1772063468482,NaN
19,Indy,24032301,24032301CH,Andre,21.0,Male,"Other, please specify",84116.0,Concerned,Only a little,1-2 times a month,Only a little,NaN,NaN,NaN,https://uofu.app.box.com/file/1770839150076,NaN,NaN
20,Indy,24032302,24032302KC,Harper,18.0,Male,Asian,84128.0,.,Only a little,Not at all,Not at all,https://uofu.app.box.com/file/1489628632116,"Theo (patterned shirt, child), Hazel (gray hoo...",NaN,https://uofu.app.box.com/integrations/officeon...,https://uofu.app.box.com/integrations/officeon...,NaN
21,Indy,24032302,24032302RL,Hazel,18.0,Female,Caucasian,84129.0,Alarmed,A great deal,1-2 times a month,A moderate amount,https://uofu.app.box.com/file/1482444110140,"Harper (black sweater, piercings), Theo",NaN,NaN,NaN,NaN
22,Indy,24032302,24032302MC,Julian,23.0,Male,"More than one race, please specify",84105.0,Alarmed,A great deal,About once a week,.,https://uofu.app.box.com/file/1489627650052,"Theo, Harper, Hazel Olive (green dress, glasse...",NaN,NaN,NaN,NaN
23,Indy,24032302,24032302KK,Olive,24.0,Female,Caucasian,84105.0,Concerned,A moderate amount,1-2 times a month,A moderate amount,https://uofu.app.box.com/file/1479920236545,"Julian, Lottie, Theo",NaN,NaN,NaN,NaN
24,Indy,24032302,24032302SAI,Theo,9.0,Male,"More than one race, please specify",84128.0,.,Don't know,.,.,https://uofu.app.box.com/file/1489631246108,"Julian, Lottie, Olive, Harper, Hazel",NaN,NaN,NaN,NaN
25,Indy,24032302,24032302SH,Lottie,41.0,Female,Caucasian,84128.0,.,Don't know,.,.,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,24032303,24032303TL,NaN,54.0,Female,Asian,84009.0,Concerned,Only a little,1-2 times a month,Only a little,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,24032304,24032304YD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,24032304,24032304AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,24032304,24032304YDSON,NaN,15.0,Male,Asian,84118.0,Concerned,A moderate amount,Not at all,Only a little,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
analysis_df_no_hartland = full_analysis_df.copy()

# Get list of Hartland participant IDs
hartland_ids = hartland_participant_index['ida'].dropna().tolist()

# Check which Hartland IDs are not in the analysis dataframe
missing_ids = []
for ida in hartland_ids:
    if ida not in full_analysis_df['ida'].values:
        missing_ids.append(ida)
        print(f"ID not found in analysis dataframe: {ida}")

# Remove Hartland participants from the analysis dataframe
analysis_df_no_hartland = analysis_df_no_hartland[~analysis_df_no_hartland['ida'].isin(hartland_ids)]

# Print summary
print(f"Removed {len(hartland_ids) - len(missing_ids)} Hartland participants from the dataset")
print(f"Original dataset size: {len(full_analysis_df)}")
print(f"New dataset size: {len(analysis_df_no_hartland)}")
display(analysis_df_no_hartland)

ID not found in analysis dataframe: 24022417CG
ID not found in analysis dataframe: 24032302RL
ID not found in analysis dataframe: 24032304YD
ID not found in analysis dataframe: 24032304AL
Removed 26 Hartland participants from the dataset
Original dataset size: 191
New dataset size: 165

In [6]:
# Remove unknown participant with ID 24032305U (the date corresponds with a Hartland visit)
if '24032305U' in analysis_df_no_hartland['ida'].values:
    analysis_df_no_hartland = analysis_df_no_hartland[analysis_df_no_hartland['ida'] != '24032305U']
    print(f"Removed participant with ID 24032305U")
    print(f"Updated dataset size: {len(analysis_df_no_hartland)}")
else:
    print(f"Participant with ID 24032305U not found in the dataset")

# Display the updated dataframe
display(analysis_df_no_hartland)

Removed participant with ID 24032305U
Updated dataset size: 164

,start_date,end_date,status,ip_address,progress,duration_in_seconds,finished,recorded_date,response_id,recipient_last_name,...,q49_48,q49_49,q49_50,q51_1,q51_2,q51_3,q51_4,q51_5,q51_6,q51_7
0,2024-04-05 14:12:54,2024-04-05 15:57:31,IP Address,155.98.131.1,100.0,6276.0,1.0,2024-04-05 15:57:31,R_2dPUXEtypfBvZhD,NaN,...,A little bit,Not at all,Not at all,A lot,A lot,A lot,A lot,A little bit,Moderately,A lot
1,2024-03-13 18:59:27,2024-03-13 20:15:18,IP Address,155.98.131.5,100.0,4550.0,1.0,2024-03-13 20:15:19,R_7PAooFY6nTwIqA7,NaN,...,A little bit,Not at all,Not at all,A great deal,A great deal,A great deal,Moderately,Not at all,Moderately,A lot
2,2024-03-23 13:49:19,2024-04-03 19:27:57,IP Address,155.98.131.5,100.0,970717.0,1.0,2024-04-03 19:27:58,R_73AteLV2ZE5L4GJ,NaN,...,A lot,Moderately,A lot,Moderately,A little bit,A little bit,A little bit,A little bit,Moderately,A little bit
3,2024-01-26 15:51:59,2024-01-26 16:41:06,IP Address,155.98.131.2,100.0,2946.0,1.0,2024-01-26 16:41:06,R_3uP2DqVWkGDu8La,NaN,...,Extremely,Moderately,Not at all,Moderately,A lot,A great deal,Moderately,A little bit,Moderately,Moderately
4,2024-01-24 16:32:42,2024-01-24 19:27:07,IP Address,155.98.131.2,100.0,10464.0,1.0,2024-01-24 19:27:07,R_7OiAhfM2TEkyQdM,NaN,...,A lot,Moderately,Not at all,Not at all,Not at all,Not at all,Not at all,A little bit,Not at all,Not at all
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2024-04-06 14:34:46,2024-04-06 15:31:05,IP Address,155.98.131.5,100.0,3378.0,1.0,2024-04-06 15:31:05,R_3fNzlkOukIhRV9V,NaN,...,Not at all,Moderately,Not at all,A great deal,A great deal,A great deal,A great deal,A little bit,A great deal,A great deal
187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN